[global]
keyboard = "en-us"
country = "us"
fqdn = "dissect-proxmox-9.smoketest"
mailto = "root@localhost"
timezone = "UTC"
root-password = "password"

[network]
source = "from-dhcp"

[disk-setup]
filesystem = "ext4"
disk-list = ["vda"]
